services:
  network-service:
    image: alpine
    container_name: sciol-network
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}" # MinIO API
    command: tail -f /dev/null
    networks:
      - sciol-network


  postgresql:
    image: pgvector/pgvector:pg17
    container_name: lobe-postgres
    # 不需要暴露端口，因为只有后端服务需要连接数据库
    # ports:
    #   - '5432:5432'
    volumes:
      - 'data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=${LOBE_DB_NAME}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - sciol-network


networks:
  sciol-network:
    driver: bridge


volumes:
  sciol-postgres-data:
    driver: local
